#!/bin/bash
set -e

CONFIG_FILE="/var/www/signaltrace/includes/config.local.php"
DB_FILE="/var/www/signaltrace/data/database.db"
GEOIP_CONF="/etc/GeoIP.conf"

# ============================================================
# Validate required environment variables
# ============================================================

if [ -z "$SIGNALTRACE_ADMIN_USERNAME" ]; then
    echo "ERROR: SIGNALTRACE_ADMIN_USERNAME is not set." >&2
    exit 1
fi

if [ -z "$SIGNALTRACE_ADMIN_PASSWORD_HASH" ]; then
    echo "ERROR: SIGNALTRACE_ADMIN_PASSWORD_HASH is not set." >&2
    echo "Generate one with: php -r \"echo password_hash('yourpassword', PASSWORD_DEFAULT) . PHP_EOL;\"" >&2
    exit 1
fi

if [ -z "$SIGNALTRACE_VISITOR_HASH_SALT" ]; then
    echo "ERROR: SIGNALTRACE_VISITOR_HASH_SALT is not set." >&2
    echo "Generate one with: openssl rand -hex 64" >&2
    exit 1
fi

# ============================================================
# Generate config.local.php from environment variables
# ============================================================

echo "Generating config.local.php..."

cat > "$CONFIG_FILE" <<PHP
<?php
// Auto-generated by Docker entrypoint. Do not edit manually.
// To change these values, update the environment variables and restart the container.

define('ADMIN_USERNAME',      '${SIGNALTRACE_ADMIN_USERNAME}');
define('ADMIN_PASSWORD_HASH', '${SIGNALTRACE_ADMIN_PASSWORD_HASH}');
define('VISITOR_HASH_SALT',   '${SIGNALTRACE_VISITOR_HASH_SALT}');
PHP

if [ -n "$SIGNALTRACE_EXPORT_API_TOKEN" ]; then
    echo "define('EXPORT_API_TOKEN', '${SIGNALTRACE_EXPORT_API_TOKEN}');" >> "$CONFIG_FILE"
fi

if [ -n "$SIGNALTRACE_TRUSTED_PROXY_IP" ]; then
    echo "define('TRUSTED_PROXY_IP', '${SIGNALTRACE_TRUSTED_PROXY_IP}');" >> "$CONFIG_FILE"
fi

chown www-data:www-data "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"

echo "config.local.php written."

# ============================================================
# Initialise the database on first run
# ============================================================

if [ ! -f "$DB_FILE" ]; then
    echo "Initialising database..."
    sqlite3 "$DB_FILE" < /var/www/signaltrace/db/schema.sql
    chown www-data:www-data "$DB_FILE"
    chmod 664 "$DB_FILE"
    echo "Database initialised."
else
    echo "Database already exists, skipping initialisation."
fi

# ============================================================
# Set up GeoIP if credentials are provided
# ============================================================

if [ -n "$MAXMIND_ACCOUNT_ID" ] && [ -n "$MAXMIND_LICENSE_KEY" ]; then
    echo "Configuring GeoIP..."

    cat > "$GEOIP_CONF" <<GEOIP
AccountID ${MAXMIND_ACCOUNT_ID}
LicenseKey ${MAXMIND_LICENSE_KEY}
EditionIDs GeoLite2-ASN GeoLite2-Country
DatabaseDirectory /var/lib/GeoIP
GEOIP

    # Download databases if they don't exist yet
    if [ ! -f "/var/lib/GeoIP/GeoLite2-ASN.mmdb" ]; then
        echo "Downloading GeoIP databases..."
        geoipupdate || echo "WARNING: GeoIP download failed. Enrichment will be unavailable until databases are present."
    else
        echo "GeoIP databases already present."
    fi
else
    echo "MAXMIND_ACCOUNT_ID or MAXMIND_LICENSE_KEY not set — GeoIP enrichment will be unavailable."
fi

# ============================================================
# Start Apache
# ============================================================

exec "$@"
