#!/bin/bash
set -e

CONFIG_FILE="/var/www/signaltrace/includes/config.local.php"
DB_FILE="/var/www/signaltrace/data/database.db"
GEOIP_CONF="/etc/GeoIP.conf"

# ============================================================
# Validate required environment variables
# ============================================================
if [ -z "$SIGNALTRACE_ADMIN_USERNAME" ]; then
    echo "ERROR: SIGNALTRACE_ADMIN_USERNAME is not set." >&2
    exit 1
fi
if [ -z "$SIGNALTRACE_ADMIN_PASSWORD_HASH" ]; then
    echo "ERROR: SIGNALTRACE_ADMIN_PASSWORD_HASH is not set." >&2
    echo "Generate one with: php -r \"echo password_hash('yourpassword', PASSWORD_DEFAULT) . PHP_EOL;\"" >&2
    exit 1
fi
if [ -z "$SIGNALTRACE_VISITOR_HASH_SALT" ]; then
    echo "ERROR: SIGNALTRACE_VISITOR_HASH_SALT is not set." >&2
    echo "Generate one with: openssl rand -hex 64" >&2
    exit 1
fi

# ============================================================
# Generate config.local.php from environment variables
# ============================================================
echo "Generating config.local.php..."
printf '<?php\n// Auto-generated by Docker entrypoint. Do not edit manually.\n// To change these values, update the environment variables and restart the container.\n\n' > "$CONFIG_FILE"

# Required
printf "define('ADMIN_USERNAME',      '%s');\n" "$SIGNALTRACE_ADMIN_USERNAME"  >> "$CONFIG_FILE"
printf "define('ADMIN_PASSWORD_HASH', '%s');\n" "$SIGNALTRACE_ADMIN_PASSWORD_HASH" >> "$CONFIG_FILE"
printf "define('VISITOR_HASH_SALT',   '%s');\n" "$SIGNALTRACE_VISITOR_HASH_SALT"   >> "$CONFIG_FILE"

# Optional — only written when set
if [ -n "$SIGNALTRACE_EXPORT_API_TOKEN" ]; then
    printf "define('EXPORT_API_TOKEN',    '%s');\n" "$SIGNALTRACE_EXPORT_API_TOKEN" >> "$CONFIG_FILE"
fi
if [ -n "$SIGNALTRACE_TRUSTED_PROXY_IP" ]; then
    printf "define('TRUSTED_PROXY_IP',    '%s');\n" "$SIGNALTRACE_TRUSTED_PROXY_IP" >> "$CONFIG_FILE"
fi
if [ -n "$AUTH_MAX_FAILURES" ]; then
    printf "define('AUTH_MAX_FAILURES',   %s);\n" "$AUTH_MAX_FAILURES" >> "$CONFIG_FILE"
fi
if [ -n "$AUTH_LOCKOUT_SECS" ]; then
    printf "define('AUTH_LOCKOUT_SECS',   %s);\n" "$AUTH_LOCKOUT_SECS" >> "$CONFIG_FILE"
fi
if [ -n "$SELF_REFERER_DOMAIN" ]; then
    printf "define('SELF_REFERER_DOMAIN', '%s');\n" "$SELF_REFERER_DOMAIN" >> "$CONFIG_FILE"
fi

# Cloudflare Access
if [ "${CF_ACCESS_ENABLED}" = "true" ] && [ -n "$CF_ACCESS_AUD" ] && [ -n "$CF_ACCESS_TEAM_DOMAIN" ]; then
    printf "\n// Cloudflare Access\n"                                                   >> "$CONFIG_FILE"
    printf "define('CF_ACCESS_ENABLED',     true);\n"                                  >> "$CONFIG_FILE"
    printf "define('CF_ACCESS_AUD',         '%s');\n" "$CF_ACCESS_AUD"                 >> "$CONFIG_FILE"
    printf "define('CF_ACCESS_TEAM_DOMAIN', '%s');\n" "$CF_ACCESS_TEAM_DOMAIN"         >> "$CONFIG_FILE"
fi

# Demo mode — display-only credentials appear in the reset countdown banner
if [ "${DEMO_MODE}" = "true" ]; then
    printf "\n// Demo mode\n"                                                           >> "$CONFIG_FILE"
    printf "define('DEMO_MODE',             true);\n"                                  >> "$CONFIG_FILE"
    if [ -n "$DEMO_ADMIN_USERNAME" ]; then
        printf "define('DEMO_ADMIN_USERNAME', '%s');\n" "$DEMO_ADMIN_USERNAME"         >> "$CONFIG_FILE"
    fi
    if [ -n "$DEMO_ADMIN_PASSWORD" ]; then
        printf "define('DEMO_ADMIN_PASSWORD', '%s');\n" "$DEMO_ADMIN_PASSWORD"         >> "$CONFIG_FILE"
    fi
fi

# Email alerting — SMTP credentials only (thresholds/recipient configured in Settings UI)
# These are intentionally NOT stored in the database — keeping them here prevents
# exposure through the admin UI or a database read.
if [ -n "$EMAIL_SMTP_HOST" ]; then
    printf "\n// Email alerting — SMTP credentials\n"                                  >> "$CONFIG_FILE"
    printf "define('EMAIL_SMTP_HOST',       '%s');\n" "$EMAIL_SMTP_HOST"               >> "$CONFIG_FILE"
    printf "define('EMAIL_SMTP_PORT',       %s);\n"   "${EMAIL_SMTP_PORT:-587}"        >> "$CONFIG_FILE"
    printf "define('EMAIL_SMTP_ENCRYPTION', '%s');\n" "${EMAIL_SMTP_ENCRYPTION:-tls}"  >> "$CONFIG_FILE"
    printf "define('EMAIL_SMTP_USER',       '%s');\n" "$EMAIL_SMTP_USER"               >> "$CONFIG_FILE"
    printf "define('EMAIL_SMTP_PASS',       '%s');\n" "$EMAIL_SMTP_PASS"               >> "$CONFIG_FILE"
    printf "define('EMAIL_SMTP_FROM',       '%s');\n" "${EMAIL_SMTP_FROM:-$EMAIL_SMTP_USER}" >> "$CONFIG_FILE"
fi

chown www-data:www-data "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"
echo "config.local.php written."

# ============================================================
# Initialise the database on first run
# ============================================================
if [ ! -f "$DB_FILE" ]; then
    echo "Initialising database..."
    sqlite3 "$DB_FILE" < /var/www/signaltrace/db/schema.sql
    chown www-data:www-data "$DB_FILE"
    chmod 664 "$DB_FILE"
    echo "Database initialised."
else
    echo "Database already exists, skipping initialisation."
fi

# ============================================================
# Set up GeoIP if credentials are provided
# ============================================================
if [ -n "$MAXMIND_ACCOUNT_ID" ] && [ -n "$MAXMIND_LICENSE_KEY" ]; then
    echo "Configuring GeoIP..."
    cat > "$GEOIP_CONF" <<GEOIP
AccountID ${MAXMIND_ACCOUNT_ID}
LicenseKey ${MAXMIND_LICENSE_KEY}
EditionIDs GeoLite2-ASN GeoLite2-Country
DatabaseDirectory /var/lib/GeoIP
GEOIP
    if [ ! -f "/var/lib/GeoIP/GeoLite2-ASN.mmdb" ]; then
        echo "Downloading GeoIP databases..."
        geoipupdate || echo "WARNING: GeoIP download failed. Enrichment will be unavailable until databases are present."
    else
        echo "GeoIP databases already present."
    fi
else
    echo "MAXMIND_ACCOUNT_ID or MAXMIND_LICENSE_KEY not set — GeoIP enrichment will be unavailable."
fi

# ============================================================
# Start Apache
# ============================================================
exec "$@"
