<?php

declare(strict_types=1);

/* ======================================================
   PIXEL HANDLER
   ====================================================== */
function handlePixelRequest(PDO $pdo, string $path): void
{
    if (!preg_match('#^/pixel/(.+)\.gif$#', $path, $matches)) {
        return;
    }

    $token = trim($matches[1], '/');
    $link  = getLinkByToken($pdo, $token);

    if ($link) {
        $pixelData               = collectRequestData($path, $pdo);
        $pixelData['event_type'] = 'pixel';

        logClick($pdo, [
            'id'          => $link['id'] ?? null,
            'token'       => 'pixel:' . $token,
            'destination' => '',
        ], $pixelData);
    }

    header('Content-Type: image/gif');
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    echo base64_decode('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==');
    exit;
}

/* ======================================================
   THREAT FEED HELPERS
   ====================================================== */

/**
 * Emit a threat feed response for a given set of IPs in the requested format.
 * $family is 'ipv4' or 'ipv6' — used only for the iptables chain name comment.
 */
function emitFeed(array $ips, string $format, string $family): void
{
    $suffix = $family === 'ipv6' ? '/128' : '/32';
    $chain  = $family === 'ipv6' ? 'ip6tables' : 'iptables';

    switch ($format) {
        case 'nginx':
            header('Content-Type: text/plain');
            header('Cache-Control: no-store');
            foreach ($ips as $ip) {
                echo 'deny ' . $ip . ';' . "\n";
            }
            break;

        case 'iptables':
            header('Content-Type: text/plain');
            header('Cache-Control: no-store');
            echo '# Generated by SignalTrace — ' . date('Y-m-d H:i:s T') . "\n";
            echo '# Apply with: ' . $chain . '-restore < this-file' . "\n";
            echo '*filter' . "\n";
            foreach ($ips as $ip) {
                echo '-A INPUT -s ' . $ip . ' -j DROP' . "\n";
            }
            echo 'COMMIT' . "\n";
            break;

        case 'cidr':
            header('Content-Type: text/plain');
            header('Cache-Control: no-store');
            foreach ($ips as $ip) {
                echo $ip . $suffix . "\n";
            }
            break;

        default: // plain text, one per line
            header('Content-Type: text/plain');
            header('Cache-Control: no-store');
            foreach ($ips as $ip) {
                echo $ip . "\n";
            }
            break;
    }
    exit;
}

/* ======================================================
   THREAT FEED ROUTES
   ====================================================== */
function handleThreatFeed(PDO $pdo, array $settings, string $path): void
{
    $enabled = ($settings['threat_feed_enabled'] ?? '1') === '1';
    if (!$enabled) {
        header('Content-Type: text/plain');
        echo '';
        exit;
    }

    // Intel export formats — MISP and STIX 2.1
    if ($path === '/feed/misp.json') {
        header('Content-Type: application/json');
        header('Cache-Control: no-store');
        header('Content-Disposition: attachment; filename="signaltrace-misp-' . date('Y-m-d') . '.json"');
        echo json_encode(buildMispExport($pdo), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        exit;
    }

    if ($path === '/feed/stix.json') {
        header('Content-Type: application/json');
        header('Cache-Control: no-store');
        header('Content-Disposition: attachment; filename="signaltrace-stix-' . date('Y-m-d') . '.json"');
        echo json_encode(buildStixExport($pdo), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        exit;
    }

    // Determine address family and format from path
    // IPv4: /feed/ips.txt  /feed/ips.nginx  /feed/ips.iptables  /feed/ips.cidr
    // IPv6: /feed/ipv6.txt /feed/ipv6.nginx /feed/ipv6.iptables /feed/ipv6.cidr
    if (str_starts_with($path, '/feed/ipv6.')) {
        $family = 'ipv6';
        $ext    = substr($path, strlen('/feed/ipv6.'));
        $ips    = getThreatFeedIpv6($pdo);
    } else {
        $family = 'ipv4';
        $ext    = substr($path, strlen('/feed/ips.'));
        $ips    = getThreatFeedIpv4($pdo);
    }

    $format = match ($ext) {
        'nginx'    => 'nginx',
        'iptables' => 'iptables',
        'cidr'     => 'cidr',
        default    => 'txt',
    };

    emitFeed($ips, $format, $family);
}

/* ======================================================
   EXPORTS — filter-aware, settings-aware
   /export/json  and  /export/csv
   ====================================================== */
function parseExportFilters(): array
{
    $tokenFilter   = trim((string) ($_GET['path']    ?? ''));
    $ipFilter      = trim((string) ($_GET['ip']      ?? ''));
    $visitorFilter = trim((string) ($_GET['visitor'] ?? ''));
    $knownOnly     = isset($_GET['known']) && $_GET['known'] === '1';
    $dateFrom      = trim((string) ($_GET['date_from'] ?? ''));
    $dateTo        = trim((string) ($_GET['date_to']   ?? ''));

    // Grafana passes time range as Unix ms via ${__from} and ${__to}.
    // These are handled separately by buildExportWhere using clicked_at_unix_ms
    // for precision, with confidence threshold still applied.
    $fromMs = isset($_GET['from']) && $_GET['from'] !== '' ? (int) $_GET['from'] : null;
    $toMs   = isset($_GET['to'])   && $_GET['to']   !== '' ? (int) $_GET['to']   : null;

    $manualFilters = ($tokenFilter !== '' || $ipFilter !== '' || $visitorFilter !== ''
        || $knownOnly || $dateFrom !== '' || $dateTo !== '');

    return compact('tokenFilter', 'ipFilter', 'visitorFilter', 'knownOnly', 'dateFrom', 'dateTo', 'manualFilters', 'fromMs', 'toMs');
}

function handleExport(PDO $pdo, string $format): void
{
    $f = parseExportFilters();

    $rows = exportClicks(
        $pdo,
        $f['manualFilters'],
        $f['tokenFilter']   !== '' ? $f['tokenFilter']   : null,
        $f['ipFilter']      !== '' ? $f['ipFilter']      : null,
        $f['visitorFilter'] !== '' ? $f['visitorFilter'] : null,
        $f['knownOnly'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        5000,
        $f['fromMs'],
        $f['toMs'],
    );

    if ($format === 'csv') {
        header('Content-Type: text/csv');
        header('Content-Disposition: attachment; filename="signaltrace-export-' . date('Ymd-His') . '.csv"');
        header('Cache-Control: no-store');

        if (empty($rows)) {
            exit;
        }

        $out = fopen('php://output', 'w');
        fputcsv($out, array_keys($rows[0]));
        foreach ($rows as $row) {
            fputcsv($out, $row);
        }
        fclose($out);
    } else {
        header('Content-Type: application/json');
        header('Cache-Control: no-store');
        echo json_encode($rows, JSON_PRETTY_PRINT);
    }

    exit;
}

function handleExportStats(PDO $pdo): void
{
    $f = parseExportFilters();

    $stats = exportStats(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($stats, JSON_PRETTY_PRINT);
    exit;
}

function handleExportStatsExtended(PDO $pdo): void
{
    $f = parseExportFilters();

    $stats = exportStatsExtended(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($stats, JSON_PRETTY_PRINT);
    exit;
}

function handleExportByIp(PDO $pdo): void
{
    $f     = parseExportFilters();
    $limit = max(1, min(500, (int) ($_GET['limit'] ?? 20)));

    $rows = exportByIp(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $limit,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

function handleExportByCountry(PDO $pdo): void
{
    $f     = parseExportFilters();
    $limit = max(1, min(500, (int) ($_GET['limit'] ?? 20)));

    $rows = exportByCountry(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $limit,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

function handleExportByToken(PDO $pdo): void
{
    $f           = parseExportFilters();
    $limit       = max(1, min(100, (int) ($_GET['limit'] ?? 5)));
    $labelFilter = trim((string) ($_GET['label'] ?? ''));

    $rows = exportByToken(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $limit,
        $labelFilter !== '' ? $labelFilter : null,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

function handleExportByOrg(PDO $pdo): void
{
    $f     = parseExportFilters();
    $limit = max(1, min(100, (int) ($_GET['limit'] ?? 5)));

    $rows = exportByOrg(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $limit,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

function handleExportBySignal(PDO $pdo): void
{
    $f     = parseExportFilters();
    $limit = max(1, min(100, (int) ($_GET['limit'] ?? 8)));

    $rows = exportBySignal(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $limit,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

function handleExportBehavioralSignals(PDO $pdo): void
{
    $f = parseExportFilters();

    $rows = exportBehavioralSignals(
        $pdo,
        $f['manualFilters'],
        $f['dateFrom'] !== '' ? $f['dateFrom'] : null,
        $f['dateTo']   !== '' ? $f['dateTo']   : null,
        $f['fromMs'],
        $f['toMs'],
    );

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

function handleExportOverTime(PDO $pdo): void
{
    $fromMs = isset($_GET['from']) && $_GET['from'] !== '' ? (int) $_GET['from'] : null;
    $toMs   = isset($_GET['to'])   && $_GET['to']   !== '' ? (int) $_GET['to']   : null;

    $rows = exportOverTime($pdo, $fromMs, $toMs);

    header('Content-Type: application/json');
    header('Cache-Control: no-store');
    echo json_encode($rows, JSON_PRETTY_PRINT);
    exit;
}

/* ======================================================
   ADMIN PAGE
   ====================================================== */
function handleAdminPage(PDO $pdo, array $settings): void
{
    requireAdminAuth();

    $appName             = $settings['app_name']             ?? 'SignalTrace';
    $baseUrl             = trim((string) ($settings['base_url']             ?? ''));
    $defaultRedirectUrl  = trim((string) ($settings['default_redirect_url'] ?? 'https://example.com/'));
    $unknownPathBehavior = trim((string) ($settings['unknown_path_behavior'] ?? 'redirect'));
    $pixelEnabled        = ($settings['pixel_enabled']        ?? '1') === '1';
    $noiseFilterEnabled  = ($settings['noise_filter_enabled'] ?? '1') === '1';

    $tokenFilter   = trim((string) ($_GET['token']   ?? ''));
    $ipFilter      = trim((string) ($_GET['ip']      ?? ''));
    $visitorFilter = trim((string) ($_GET['visitor'] ?? ''));
    $hostFilter    = trim((string) ($_GET['host']    ?? ''));
    $knownOnly     = isset($_GET['known'])    && $_GET['known']    === '1';
    $dateFrom      = trim((string) ($_GET['date_from'] ?? ''));
    $dateTo        = trim((string) ($_GET['date_to']   ?? ''));
    $asnRules      = getAsnRules($pdo);

    // Pagination
    $pageSize    = max(10, (int) ($settings['page_size'] ?? 50));
    $currentPage = max(1, (int) ($_GET['page'] ?? 1));
    $offset      = ($currentPage - 1) * $pageSize;

    [$clicks, $totalCount] = getRecentClicksAdvancedFilteredPaged(
        $pdo,
        $pageSize,
        $offset,
        $tokenFilter   !== '' ? $tokenFilter   : null,
        $ipFilter      !== '' ? $ipFilter      : null,
        $visitorFilter !== '' ? $visitorFilter : null,
        $knownOnly,
        $dateFrom !== '' ? $dateFrom : null,
        $dateTo   !== '' ? $dateTo   : null,
        $hostFilter !== '' ? $hostFilter : null,
    );

    $totalPages  = $pageSize > 0 ? max(1, (int) ceil($totalCount / $pageSize)) : 1;
    // Clamp current page now that we know the total — prevents wasteful
    // large-offset queries on subsequent requests.
    $currentPage = min($currentPage, $totalPages);

    $links       = getAllLinks($pdo);
    $tokenCounts = getClickCountsByToken(
        $pdo,
        $knownOnly,
        $dateFrom !== '' ? $dateFrom : null,
        $dateTo   !== '' ? $dateTo   : null,
    );

    $skipPatterns  = getSkipPatterns($pdo);
    $showTopTokens = isset($_GET['show_top_tokens']) && $_GET['show_top_tokens'] === '1';
    $showAll       = isset($_GET['show_all'])        && $_GET['show_all']        === '1';

    // Per-IP summary when filtering by a single exact IP
    $ipSummary = null;
    if ($ipFilter !== '' && !str_contains($ipFilter, '%')) {
        $ipSummary = getIpSummary($pdo, $ipFilter);
    }

    $refreshParams = [];
    if ($tokenFilter   !== '') $refreshParams['token']           = $tokenFilter;
    if ($ipFilter      !== '') $refreshParams['ip']              = $ipFilter;
    if ($visitorFilter !== '') $refreshParams['visitor']         = $visitorFilter;
    if ($hostFilter    !== '') $refreshParams['host']            = $hostFilter;
    if ($knownOnly)            $refreshParams['known']           = '1';
    if ($showTopTokens)        $refreshParams['show_top_tokens'] = '1';
    if ($showAll)              $refreshParams['show_all']        = '1';
    if ($dateFrom      !== '') $refreshParams['date_from']       = $dateFrom;
    if ($dateTo        !== '') $refreshParams['date_to']         = $dateTo;

    $refreshUrl = '/admin' . (!empty($refreshParams) ? '?' . http_build_query($refreshParams) : '');

    renderAdminPage(
        $appName,
        $baseUrl,
        $defaultRedirectUrl,
        $unknownPathBehavior,
        $pixelEnabled,
        $noiseFilterEnabled,
        $tokenFilter,
        $ipFilter,
        $visitorFilter,
        $knownOnly,
        $clicks,
        $totalCount,
        $totalPages,
        $currentPage,
        $pageSize,
        $links,
        $tokenCounts,
        $skipPatterns,
        $asnRules,
        $refreshUrl,
        $ipSummary,
        $hostFilter,
    );

    exit;
}

/* ======================================================
   TRACKED REQUEST
   ====================================================== */
function handleTrackedRequest(PDO $pdo, string $path, array $settings, array $skipPatternMap): void
{
    $defaultRedirectUrl  = trim((string) ($settings['default_redirect_url']  ?? 'https://example.com/'));
    $unknownPathBehavior = trim((string) ($settings['unknown_path_behavior'] ?? 'redirect'));
    $noiseFilterEnabled  = ($settings['noise_filter_enabled'] ?? '1') === '1';

    $token       = normalizeTokenFromPath($path);
    $requestData = collectRequestData($path, $pdo);
    $link        = getLinkByToken($pdo, $token);

    if (
        !$link
        && $noiseFilterEnabled
        && shouldSkipLogging($token, $path, $requestData['user_agent'] ?? null, $skipPatternMap)
    ) {
        redirectOr404($unknownPathBehavior, $defaultRedirectUrl);
    }

    if ($link) {
        logClick($pdo, $link, $requestData);
        maybeFireTokenAlert($pdo, $requestData);
        maybeFireTokenEmailAlert($pdo, $requestData);
        maybeFireAlert($pdo, $requestData);
        maybeFireEmailAlert($pdo, $requestData);
        maybeRunAutoCleanup($pdo);

        $destination = (string) ($link['destination'] ?? '');
        if (!isSafeRedirectUrl($destination)) {
            error_log('SignalTrace: unsafe destination for token ' . $token . ': ' . $destination);
            redirectOr404($unknownPathBehavior, $defaultRedirectUrl);
        }

        // Rate limit: if this IP has hit this token too many times within the
        // configured window, return 429 instead of redirecting. The click is
        // still logged above — rate limiting only affects the redirect response.
        if (isRedirectRateLimited($pdo, (string) ($requestData['ip'] ?? ''), $token)) {
            http_response_code(429);
            header('Retry-After: ' . (int) getSetting($pdo, 'redirect_rate_limit_window', '60'));
            exit('Too many requests.');
        }

        header('Location: ' . $destination, true, 302);
        exit;
    }

    logClick($pdo, [
        'id'          => null,
        'token'       => $token,
        'destination' => '',
    ], $requestData);

    maybeFireAlert($pdo, $requestData);
    maybeFireEmailAlert($pdo, $requestData);
    maybeRunAutoCleanup($pdo);

    redirectOr404($unknownPathBehavior, $defaultRedirectUrl);
}
